"""
LaTeX Converter Module
Converts parsed music notation to LaTeX format using LilyPond syntax
"""

from typing import List, Dict, Any
from partition_parser import Note


class LaTeXConverter:
    """Converts music notes to LaTeX format using LilyPond"""
    
    def __init__(self, metadata: Dict[str, Any] = None):
        self.metadata = metadata or {}
        self.title = self.metadata.get('title', 'Untitled')
        self.tempo = self.metadata.get('tempo', 120)
        self.time_signature = self.metadata.get('time_signature', '4/4')
        self.key = self.metadata.get('key', 'C')
        
    def convert_to_lilypond(self, notes: List[Note]) -> str:
        """
        Convert notes to LilyPond syntax (can be embedded in LaTeX)
        LilyPond is the standard for music notation in LaTeX
        """
        # Build the note sequence
        note_sequence = []
        for note in notes:
            note_sequence.append(note.to_latex())
        
        notes_str = ' '.join(note_sequence)
        
        # Create LilyPond code
        lilypond_code = f'''\\version "2.20.0"

\\header {{
  title = "{self.title}"
  tagline = ""
}}

\\score {{
  \\new Staff {{
    \\tempo 4 = {self.tempo}
    \\time {self.time_signature}
    \\key {self._convert_key_to_lilypond()} \\major
    {{
      {notes_str}
    }}
  }}
  \\layout {{ }}
  \\midi {{ }}
}}
'''
        return lilypond_code
    
    def convert_to_latex_document(self, notes: List[Note]) -> str:
        """
        Convert notes to a complete LaTeX document with embedded LilyPond
        """
        lilypond_music = self.convert_to_lilypond(notes)
        
        latex_document = f'''\\documentclass{{article}}
\\usepackage{{libertine}}
\\usepackage[T1]{{fontenc}}

% To compile this document:
% 1. Save as music.lytex
% 2. Run: lilypond-book --pdf music.lytex
% 3. Run: pdflatex music.tex

\\begin{{document}}

\\title{{{self.title}}}
\\author{{Generated by PartitionReader}}
\\date{{\\today}}
\\maketitle

\\section*{{Music Score}}

This score was automatically generated from a music partition file.

\\begin{{center}}
\\begin{{lilypond}}
{lilypond_music}
\\end{{lilypond}}
\\end{{center}}

\\section*{{Details}}

\\begin{{itemize}}
  \\item \\textbf{{Tempo:}} {self.tempo} BPM
  \\item \\textbf{{Time Signature:}} {self.time_signature}
  \\item \\textbf{{Key:}} {self.key} Major
  \\item \\textbf{{Number of Notes:}} {len(notes)}
\\end{{itemize}}

\\end{{document}}
'''
        return latex_document
    
    def _convert_key_to_lilypond(self) -> str:
        """Convert key signature to LilyPond format"""
        key_map = {
            'C': 'c',
            'G': 'g',
            'D': 'd',
            'A': 'a',
            'E': 'e',
            'B': 'b',
            'F': 'f',
            'Bb': 'bes',
            'Eb': 'ees',
            'Ab': 'aes',
            'Db': 'des',
            'Gb': 'ges',
            'C#': 'cis',
            'F#': 'fis'
        }
        return key_map.get(self.key, 'c')
    
    def save_to_file(self, notes: List[Note], filename: str, 
                     full_document: bool = True):
        """
        Save the LaTeX/LilyPond output to a file
        
        Args:
            notes: List of Note objects to convert
            filename: Output filename
            full_document: If True, creates full LaTeX document; 
                          if False, only LilyPond code
        """
        if full_document:
            content = self.convert_to_latex_document(notes)
        else:
            content = self.convert_to_lilypond(notes)
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"LaTeX output saved to: {filename}")
        
        if full_document:
            print("\nTo compile the LaTeX document with music notation:")
            print(f"1. lilypond-book --pdf {filename}")
            print(f"2. cd out/")
            print(f"3. pdflatex {filename.replace('.lytex', '.tex')}")
